name: Greet World
run-name: Greet everyone from list

on:
  workflow_dispatch: {}

jobs:
  greet_everyone:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        people:
          - Praveen
          - Priya
          - David
    steps:
      - name: Call custom action
        id: custom_action
        uses: PraveenDharmaraj92/hello-world-action@v2
        with:
          name: ${{matrix.people}}
      - name: Display length of name
        run: |
          echo "The length of name is ${{steps.custom_action.outputs.name_length}}"
